### ISSUE TITLE
AutoImagrNBI - the signing

### ISSUE THREAD

**Issue by macmule** [autopkg/clburlison-recipes#4]
Just a heads up, pre-release up: https://github.com/macmule/AutoImagrNBI/releases/tag/1.3.4

Hopeful for next week release, & is signed.

Authority=Mac Developer: Ben Toms (L7N6BNQQEU)

**Comment by macmule** [comment]
1.3.4 released & signed :)

**Comment by clburlison** [comment]
Thanks for the heads up @macmule!
